### ISSUE TITLE
ReadMe

### ISSUE THREAD

**Issue by clairekrogers** [stevemboyle/TixStarter#1]
- MVP: bullet points appear to be copy from demo project.  Update with info specific to your project.  
- Auth needs to be frontend
- Don't need 4 days for CSS and don't want to leave it all until the end.  Do CSS as you go, making sure everything has basic styling. Spread the 4 days out to showtimes and tickets, or bonus features.

**Comment by stevemboyle** [comment]
Can we talk a little bit about approaches to styling this afternoon?

Thanks!

**Comment by stevemboyle** [comment]
MVP bullet points updated.
